apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-producer
  namespace: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-producer
  template:
    metadata:
      labels:
        app: postgres-producer
    spec:
      containers:
        - name: producer
          image: postgres-producer:local
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_HOST
              value: postgres-postgresql.producer.svc.cluster.local
            - name: POSTGRES_DB
              value: appdb
            - name: POSTGRES_USER
              value: app
            - name: POSTGRES_PASSWORD
              value: app
            - name: POSTGRES_PORT
              value: "5432"
            - name: KAFKA_BOOTSTRAP
              value: my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
            - name: KAFKA_TOPIC
              value: events
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"